/// Flutter icons IkonEnsiklotari
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IkonEnsiklotari
///      fonts:
///       - asset: fonts/IkonEnsiklotari.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IkonEnsiklotari {
  IkonEnsiklotari._();

  static const _kFontFam = 'IkonEnsiklotari';
  static const String? _kFontPkg = null;

  static const IconData email = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
